import java.util.List;
import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        OkCupid okCupid = new OkCupid();
        Profiles profileList = okCupid.getJsonProfileList();
        Map<Integer,Profile> profiles = okCupid.getProfileObject(profileList);
        List<Results> results = okCupid.getResultsList(profiles);
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String JSONOutput = gson.toJson(results);
        JsonParser jp = new JsonParser();
        JsonElement je = jp.parse(JSONOutput);
        String prettyJsonString = gson.toJson(je);
        System.out.println(prettyJsonString);
    }
}
